runtime: python39 # or another supported version
env: standard
entrypoint: flask run --host 0.0.0.0 --port 8080

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

includes:
  - secret.yaml
