version: "3.1"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
      - ./configdb:/data/configdb

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${PASSWORD}

  flask:
    build: .
    volumes:
      - .:/code/
    tty: true
    env_file:
      - .env
    depends_on:
      - mongo
      - mongo-express
    ports:
      - "5000:5000"
    environment:
      TZ: "Asia/Tokyo"
      FLASK_ENV: "development"
    command: flask run --host 0.0.0.0 --port 5000
