version: "3"

services:
  # ローカル用DB
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${PASSWORD}
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
      - ./configdb:/data/configdb

  # ローカル用DBのGUI確認用
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${PASSWORD}

  flask:
    build: .
    # image: 531974357576.dkr.ecr.ap-northeast-1.amazonaws.com/youtubematome:latest
    volumes:
      - .:/code/
    tty: true
    env_file:
      - .env
    depends_on:
      - mongo
      - mongo-express
    ports:
      - "8080:8080"
    environment:
      TZ: "Asia/Tokyo"
      FLASK_ENV: "development"
    command: flask run --host 0.0.0.0 --port 8080
